#!/bin/bash

# Copyright 2023 GencoreOperative
# 
# Licensed under Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International Public License

docker run --rm -ti gencore/alpaca.cpp:latest --prompt "$@"